name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: eslint
        run: |
          npm install --save-dev eslint
          npm run lint
      - name: tsc
        run: |
          npm install  --save-dev typescript
          npx tsc

    
